# Site settings
title: saminiir's hacker blog
email: saminiir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Yet Another Hacker Blog (YAHB). UNIX, Networking, Self-Improvement.
#baseurl: # the subpath of your site, e.g. /blog/
url: "https://www.saminiir.com" # the base hostname & protocol for your site
twitter_username: saminiir
github_username:  saminiir

# Build settings
markdown: kramdown

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about.html
